spring:
  application:
    name: service-registry
server:
  port: 8720
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8720/eureka