spring:
  application:
    name: app-service
  datasource:
    url: jdbc:mysql://localhost:3306/resto?serverTimeZone=UTC
    username: resto
    password: resto
server:
  port: 8810
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8720/eureka
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
